### ISSUE TITLE
Dockerized Trusted Connector on Windows does not receive correct external IP

### ISSUE THREAD

**Issue by rizktouma** [Fraunhofer-AISEC/trusted-connector#82]
**Describe the bug**
When running the Trusted Connector in a Docker container on Windows, any connections from external IPs are seen inside the container with the local docker gateway IP (e.g. 172.18.0.1). This makes it impossible to establish a connection between two connectors in different networks with demo certificates that are not local. For instance, we have a provider connector with its own demo certificate and another consumer connector with its own certificate. Both certificates were issued for the public IP addresses and domain names of the machines where the connectors are hosted.

However, when a connection is established from the consumer, the provider receives the local docker gateway IP instead of the public IP of the machine where the consumer is hosted. This causes a mismatch with the IP specified in the consumer certificate which results in the following error:

```
java.util.concurrent.CompletionException: de.fhg.aisec.ids.idscp2.idscp_core.error.Idscp2Exception: TLS session was not valid
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
	at de.fhg.aisec.ids.idscp2.default_drivers.secure_channel.tlsv1_3.server.TLSServerThread.handshakeCompleted(TLSServerThread.kt:192) [!/:?]
	at sun.security.ssl.TransportContext$NotifyHandshake$1.run(TransportContext.java:662) [?:?]
	at sun.security.ssl.TransportContext$NotifyHandshake$1.run(TransportContext.java:659) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:?]
	at sun.security.ssl.TransportContext$NotifyHandshake.run(TransportContext.java:659) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: de.fhg.aisec.ids.idscp2.idscp_core.error.Idscp2Exception: TLS session was not valid
	at de.fhg.aisec.ids.idscp2.default_drivers.secure_channel.tlsv1_3.server.TLSServerThread.handshakeCompleted(TLSServerThread.kt:193) ~[!/:?]
	... 5 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname verification failed. Peer certificate does not belong to peer host
	at de.fhg.aisec.ids.idscp2.default_drivers.secure_channel.tlsv1_3.TLSSessionVerificationHelper.verifyTlsSession(TLSSessionVerificationHelper.kt:123) ~[!/:?]
	at de.fhg.aisec.ids.idscp2.default_drivers.secure_channel.tlsv1_3.server.TLSServerThread.handshakeCompleted(TLSServerThread.kt:173) ~[!/:?]
	... 5 more
```

**To Reproduce**
Environment:
1. Host machines must be Windows / Mac with Docker for Windows / Mac.
2. Both machines must have a public IP.
3. Certificates must be issued for the specific IP of each machine instead of the dummy "local" certificates.

1. Clone the trusted-connector repository on two machines with public IPs in two different networks.
2. Change the certificates used with ones issued for the specific public IP of the machine.
3. Run the provider connector on one machine using Docker for Windows.
4. Run the consumer on the other machine.

**Expected behavior**
The handshake should be successful and a connection should be established between the Provider and Consumer. Instead, the handshake fails because of certificate validation error.

**Screenshots and logs**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - Environment Docker version (Docker for Windows 2.3.0.3)
 - Version 4.0.0 / 5.0.0

**Additional context**
This is a known issue that affects Docker for **Windows and Mac** (in Linux it can be solved) and there's currently no official solution for it (https://github.com/docker/roadmap/issues/157 and https://github.com/docker/for-mac/issues/180). The obvious solution is to run the Trusted Connector locally without Docker containers. However, current documentation is docker-focused and does not include steps to build / run the connector outside of docker (https://industrial-data-space.github.io/trusted-connector-documentation/docs/dev_core/). So we wanted to see if someone has faced this problem before, and if you can recommend any solution.

**Comment by milux** [comment]
Hi, the solution to that issue is the usage of `extra_hosts` in Docker Compose or `--add-host` on Docker CLI.
Using that, you can map the host names used in your certificates to any (external) IP address, such that the connectors can resolve each other's IPs.

**Comment by gbrost** [comment]
Btw. I guess your problem originates since you are using Host-IPs in the certificates. The IDS demo infrastructure issues certificates based on DNS entries. Can you use host names for your setups? Then it is straight forward to use milux' advice.
